#!/bin/bash

ACTION=$1
case "$ACTION" in
  start)
    /tmp/sleepwalkingserver &
    ;;
  stop)
    kill $(cat /tmp/sleepwalkingserver.pid)
    ;;
  *)
    echo "Usage sleepwalking start|stop"
    exit 1
    ;;
esac
exit 0